// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVCfZPN62gPzJ4GnohEXktIW008PZt0A',
    appId: '1:510264891289:web:1e8f8b7be9e18ee0056508',
    messagingSenderId: '510264891289',
    projectId: 'readify-term-project',
    authDomain: 'readify-term-project.firebaseapp.com',
    storageBucket: 'readify-term-project.firebasestorage.app',
    measurementId: 'G-YFN9MHN1S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFd6AL1s3ePROLw_G1LLlCRIb3DVUCB50',
    appId: '1:510264891289:android:494b2b5ea6cde04e056508',
    messagingSenderId: '510264891289',
    projectId: 'readify-term-project',
    storageBucket: 'readify-term-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vFltSxBW33ISO1ltoc4y7E8us0JFNSw',
    appId: '1:510264891289:ios:e20e33e54e7f56c9056508',
    messagingSenderId: '510264891289',
    projectId: 'readify-term-project',
    storageBucket: 'readify-term-project.firebasestorage.app',
    iosBundleId: 'com.example.termproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8vFltSxBW33ISO1ltoc4y7E8us0JFNSw',
    appId: '1:510264891289:ios:e20e33e54e7f56c9056508',
    messagingSenderId: '510264891289',
    projectId: 'readify-term-project',
    storageBucket: 'readify-term-project.firebasestorage.app',
    iosBundleId: 'com.example.termproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVCfZPN62gPzJ4GnohEXktIW008PZt0A',
    appId: '1:510264891289:web:33b5594205bab2ef056508',
    messagingSenderId: '510264891289',
    projectId: 'readify-term-project',
    authDomain: 'readify-term-project.firebaseapp.com',
    storageBucket: 'readify-term-project.firebasestorage.app',
    measurementId: 'G-51YWFT3Q0D',
  );
}
